import 'server-only';
import { createHmac, timingSafeEqual } from 'node:crypto';

// Documents are private. Same-origin downloads are gated by session + ownership.
// For out-of-band / CDN delivery we also support short-lived signed tokens so a
// link can be emailed without exposing the object publicly.

function secret(): string {
  return process.env.DOCUMENT_URL_SECRET ?? 'dev-doc-secret';
}

function ttlSeconds(): number {
  return Number(process.env.DOCUMENT_URL_TTL_SECONDS ?? '300');
}

/** Create a signed token "<exp>.<hmac>" granting access to one document. */
export function signDocumentToken(documentId: string, now = Date.now()): string {
  const exp = Math.floor(now / 1000) + ttlSeconds();
  const mac = createHmac('sha256', secret()).update(`${documentId}.${exp}`).digest('base64url');
  return `${exp}.${mac}`;
}

/** Verify a signed token for a document. Returns true when valid and unexpired. */
export function verifyDocumentToken(documentId: string, token: string | null, now = Date.now()): boolean {
  if (!token) return false;
  const [expStr, mac] = token.split('.');
  if (!expStr || !mac) return false;
  const exp = Number(expStr);
  if (!Number.isFinite(exp) || exp * 1000 < now) return false;
  const expected = createHmac('sha256', secret()).update(`${documentId}.${exp}`).digest('base64url');
  const a = Buffer.from(mac);
  const b = Buffer.from(expected);
  return a.length === b.length && timingSafeEqual(a, b);
}

/**
 * Placeholder document body. In production, documents live in object storage
 * (S3/GCS) and this route streams the real object (PDF) via the storageKey.
 */
export function sampleDocumentBody(opts: { name: string; investorName: string; terms: string }): string {
  return [
    'AMSTERDAM CAPITAL GROUP',
    'ACG Promissory Note — Investor Portal',
    '',
    opts.name,
    '',
    `Investor: ${opts.investorName}`,
    opts.terms,
    '',
    'This is a sample document generated by the ACG portal. Production deployments',
    'serve the real executed PDF from access-controlled object storage.',
    '',
    'Returns are fixed for the term — not guaranteed.',
  ].join('\n');
}
